/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserPaymentDTO { 
    paymentId?: number;
    appointmentId?: number;
    amount?: number;
    paymentDate?: string;
    status?: string;
}

