/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserProfileDTO { 
    userId?: number;
    firstName?: string;
    lastName?: string;
    phone?: string;
    birthDate?: string;
    dni?: string;
    role?: string;
}

