/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AppointmentRequestDTO { 
    appointmentDate?: string;
    serviceId?: number;
    reason?: string;
    patientId?: number;
    dentistId?: number;
}

