/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClinicalRecordRequestDTO { 
    userId?: number;
    allergies?: string;
    medicalHistory?: string;
    familyHistory?: string;
    treatmentPlan?: string;
    evolutionNotes?: string;
}

